# -------------------------------- Clock&Reset ---------------------------------
# All clocks is distrabuted from CPLD, so the clock can be changed by CPLD.
set_property -dict {PACKAGE_PIN AD23 IOSTANDARD LVCMOS33} [get_ports clk_100m_in_pad]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports clk_32m512_in_pad]
# set_property -dict {PACKAGE_PIN AF22   IOSTANDARD LVCMOS33} [get_ports clk_reserved_in_pad]

set_property PACKAGE_PIN R8 [get_ports gtx_clk_125m_p_in_pad]
set_property PACKAGE_PIN R7 [get_ports gtx_clk_125m_n_in_pad]

set_property -dict {PACKAGE_PIN AG23 IOSTANDARD LVCMOS33} [get_ports reset_in_pad]
set_property -dict {PACKAGE_PIN AG29 IOSTANDARD LVCMOS33} [get_ports heartbeat_out_pad]

# -------------------------------- TMS320C6455 ---------------------------------
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports dsp6455_0_emif_ce2_in_pad]
# set_property -dict {PACKAGE_PIN A16    IOSTANDARD LVCMOS33} [get_ports dsp6455_0_emif_ce4_in_pad]
set_property -dict {PACKAGE_PIN C30 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_be_in_pad[0]}]
set_property -dict {PACKAGE_PIN E29 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_be_in_pad[1]}]
set_property -dict {PACKAGE_PIN B29 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_be_in_pad[2]}]
set_property -dict {PACKAGE_PIN B28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_be_in_pad[3]}]
set_property -dict {PACKAGE_PIN D27 IOSTANDARD LVCMOS33} [get_ports dsp6455_0_emif_aoe_in_pad]
set_property -dict {PACKAGE_PIN C25 IOSTANDARD LVCMOS33} [get_ports dsp6455_0_emif_awe_in_pad]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33} [get_ports dsp6455_0_emif_rnw_in_pad]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports dsp6455_0_emif_ardy_out_pad]
# set_property -dict {PACKAGE_PIN F21    IOSTANDARD LVCMOS33} [get_ports dsp6455_0_emif_ba_in_pad[0]]
# set_property -dict {PACKAGE_PIN H19    IOSTANDARD LVCMOS33} [get_ports dsp6455_0_emif_ba_in_pad[1]]
set_property -dict {PACKAGE_PIN C21 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[0]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[1]}]
set_property -dict {PACKAGE_PIN B23 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[2]}]
set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[3]}]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[4]}]
set_property -dict {PACKAGE_PIN A23 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[5]}]
set_property -dict {PACKAGE_PIN D24 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[6]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[7]}]
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[8]}]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[9]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[10]}]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[11]}]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[12]}]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[13]}]
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[14]}]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[15]}]
set_property -dict {PACKAGE_PIN E24 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[16]}]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[17]}]
set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[18]}]
set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_addr_in_pad[19]}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[0]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[1]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[2]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[3]}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[4]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[5]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[6]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[7]}]
set_property -dict {PACKAGE_PIN C29 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[8]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[9]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[10]}]
set_property -dict {PACKAGE_PIN G28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[11]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[12]}]
set_property -dict {PACKAGE_PIN F26 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[13]}]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[14]}]
set_property -dict {PACKAGE_PIN H25 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[15]}]
set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[16]}]
set_property -dict {PACKAGE_PIN A25 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[17]}]
set_property -dict {PACKAGE_PIN G23 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[18]}]
set_property -dict {PACKAGE_PIN B24 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[19]}]
set_property -dict {PACKAGE_PIN H24 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[20]}]
set_property -dict {PACKAGE_PIN A26 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[21]}]
set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[22]}]
set_property -dict {PACKAGE_PIN D29 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[23]}]
set_property -dict {PACKAGE_PIN F28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[24]}]
set_property -dict {PACKAGE_PIN A30 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[25]}]
set_property -dict {PACKAGE_PIN E30 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[26]}]
set_property -dict {PACKAGE_PIN A28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[27]}]
set_property -dict {PACKAGE_PIN A27 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[28]}]
set_property -dict {PACKAGE_PIN B27 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[29]}]
set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[30]}]
set_property -dict {PACKAGE_PIN B30 IOSTANDARD LVCMOS33} [get_ports {dsp6455_0_emif_data_inout_pad[31]}]
# set_property -dict {PACKAGE_PIN A17    IOSTANDARD LVCMOS33} [get_ports dsp6455_0_emif_hold_out_pad]

set_property -dict {PACKAGE_PIN L12 IOSTANDARD LVCMOS33} [get_ports dsp6455_0_intr_out_pad]
# set_property -dict {PACKAGE_PIN L13    IOSTANDARD LVCMOS33} [get_ports dsp6455_gpio_inout_pad9]
# set_property -dict {PACKAGE_PIN K13    IOSTANDARD LVCMOS33} [get_ports dsp6455_gpio_inout_pad10]

# -------------------------------- TMS320C6455 ---------------------------------
# From TMS320C6455 of channel 2, is required by JIDS
# set_property -dict {PACKAGE_PIN T26    IOSTANDARD LVCMOS33} [get_ports dsp6455_1_clk_in_pad]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports dsp6455_1_emif_ce4_in_pad]
set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_be_in_pad[0]}]
set_property -dict {PACKAGE_PIN K24 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_be_in_pad[1]}]
set_property -dict {PACKAGE_PIN B25 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_be_in_pad[2]}]
set_property -dict {PACKAGE_PIN AE23 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_be_in_pad[3]}]
set_property -dict {PACKAGE_PIN U27 IOSTANDARD LVCMOS33} [get_ports dsp6455_1_emif_aoe_in_pad]
set_property -dict {PACKAGE_PIN L25 IOSTANDARD LVCMOS33} [get_ports dsp6455_1_emif_awe_in_pad]
set_property -dict {PACKAGE_PIN AF23 IOSTANDARD LVCMOS33} [get_ports dsp6455_1_emif_rnw_in_pad]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports dsp6455_1_emif_ardy_out_pad]
# set_property -dict {PACKAGE_PIN D19    IOSTANDARD LVCMOS33} [get_ports dsp6455_1_emif_ba_in_pad[0]]
# set_property -dict {PACKAGE_PIN L27    IOSTANDARD LVCMOS33} [get_ports dsp6455_1_emif_ba_in_pad[1]]
set_property -dict {PACKAGE_PIN G29 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[0]}]
set_property -dict {PACKAGE_PIN G30 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[1]}]
set_property -dict {PACKAGE_PIN F27 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[2]}]
set_property -dict {PACKAGE_PIN M29 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[3]}]
set_property -dict {PACKAGE_PIN F30 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[4]}]
set_property -dict {PACKAGE_PIN E28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[5]}]
set_property -dict {PACKAGE_PIN K29 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[6]}]
set_property -dict {PACKAGE_PIN H27 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[7]}]
set_property -dict {PACKAGE_PIN R28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[8]}]
set_property -dict {PACKAGE_PIN N30 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[9]}]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[10]}]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[11]}]
set_property -dict {PACKAGE_PIN N26 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[12]}]
set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[13]}]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[14]}]
set_property -dict {PACKAGE_PIN N29 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[15]}]
set_property -dict {PACKAGE_PIN L30 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[16]}]
set_property -dict {PACKAGE_PIN L28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[17]}]
set_property -dict {PACKAGE_PIN J29 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[18]}]
set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_addr_in_pad[19]}]
set_property -dict {PACKAGE_PIN E20 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[0]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[1]}]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[2]}]
set_property -dict {PACKAGE_PIN M27 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[3]}]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[4]}]
set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[5]}]
set_property -dict {PACKAGE_PIN G27 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[6]}]
set_property -dict {PACKAGE_PIN L26 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[7]}]
set_property -dict {PACKAGE_PIN J24 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[8]}]
set_property -dict {PACKAGE_PIN M28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[9]}]
set_property -dict {PACKAGE_PIN P23 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[10]}]
set_property -dict {PACKAGE_PIN L23 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[11]}]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[12]}]
set_property -dict {PACKAGE_PIN K30 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[13]}]
set_property -dict {PACKAGE_PIN H30 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[14]}]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[15]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[16]}]
set_property -dict {PACKAGE_PIN T28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[17]}]
set_property -dict {PACKAGE_PIN N25 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[18]}]
set_property -dict {PACKAGE_PIN D28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[19]}]
set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[20]}]
set_property -dict {PACKAGE_PIN H29 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[21]}]
set_property -dict {PACKAGE_PIN J27 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[22]}]
set_property -dict {PACKAGE_PIN K25 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[23]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[24]}]
set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[25]}]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[26]}]
set_property -dict {PACKAGE_PIN J26 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[27]}]
set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[28]}]
set_property -dict {PACKAGE_PIN J28 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[29]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[30]}]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports {dsp6455_1_emif_data_inout_pad[31]}]
# set_property -dict {PACKAGE_PIN A22    IOSTANDARD LVCMOS33} [get_ports dsp6455_1_emif_hold_out_pad]

# ------------------------------------ S29GL -----------------------------------
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports s29gl_fcsb_out_pad]
set_property -dict {PACKAGE_PIN M24 IOSTANDARD LVCMOS33} [get_ports s29gl_foeb_out_pad]
set_property -dict {PACKAGE_PIN M25 IOSTANDARD LVCMOS33} [get_ports s29gl_fweb_out_pad]
set_property -dict {PACKAGE_PIN M30 IOSTANDARD LVCMOS33} [get_ports s29gl_advb_out_pad]
# set_property -dict {PACKAGE_PIN U29    IOSTANDARD LVCMOS33} [get_ports s29gl_rdwrb_out_pad]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[0]}]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[1]}]
set_property -dict {PACKAGE_PIN V24 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[2]}]
set_property -dict {PACKAGE_PIN U24 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[3]}]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[4]}]
set_property -dict {PACKAGE_PIN V21 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[5]}]
set_property -dict {PACKAGE_PIN U23 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[6]}]
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[7]}]
set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[8]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[9]}]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[10]}]
set_property -dict {PACKAGE_PIN W26 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[11]}]
set_property -dict {PACKAGE_PIN V25 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[12]}]
set_property -dict {PACKAGE_PIN V30 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[13]}]
set_property -dict {PACKAGE_PIN V29 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[14]}]
set_property -dict {PACKAGE_PIN V27 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[15]}]
set_property -dict {PACKAGE_PIN P22 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[16]}]
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[17]}]
set_property -dict {PACKAGE_PIN N24 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[18]}]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[19]}]
set_property -dict {PACKAGE_PIN N21 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[20]}]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[21]}]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33} [get_ports {s29gl_addr_out_pad[22]}]
set_property -dict {PACKAGE_PIN P24 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[0]}]
set_property -dict {PACKAGE_PIN R25 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[1]}]
set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[2]}]
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[3]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[4]}]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[5]}]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[6]}]
set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[7]}]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[8]}]
set_property -dict {PACKAGE_PIN P29 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[9]}]
set_property -dict {PACKAGE_PIN R29 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[10]}]
set_property -dict {PACKAGE_PIN P27 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[11]}]
set_property -dict {PACKAGE_PIN P28 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[12]}]
set_property -dict {PACKAGE_PIN T30 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[13]}]
set_property -dict {PACKAGE_PIN P26 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[14]}]
set_property -dict {PACKAGE_PIN R26 IOSTANDARD LVCMOS33} [get_ports {s29gl_data_inout_pad[15]}]

# --------------------------- Inter-FPGA connection ----------------------------
#  FPGA3 - FPGA4
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[0]}]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[1]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[2]}]
set_property -dict {PACKAGE_PIN L11 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[3]}]
set_property -dict {PACKAGE_PIN K11 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[4]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[5]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[6]}]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[7]}]
set_property -dict {PACKAGE_PIN J12 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[8]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[9]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[10]}]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[11]}]
set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[12]}]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[13]}]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[14]}]
set_property -dict {PACKAGE_PIN F11 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[15]}]
set_property -dict {PACKAGE_PIN E11 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[16]}]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[17]}]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[18]}]
set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[19]}]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[20]}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[21]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[22]}]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[23]}]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[24]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[25]}]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[26]}]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[27]}]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[28]}]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[29]}]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[30]}]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[31]}]
set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[32]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[33]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[34]}]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[35]}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[36]}]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[37]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[38]}]
set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS33} [get_ports {lvcmos_pre_inout_pad[39]}]

set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[0]}]
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[0]}]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[1]}]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[1]}]
set_property -dict {PACKAGE_PIN AC9 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[2]}]
set_property -dict {PACKAGE_PIN AB9 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[2]}]
set_property -dict {PACKAGE_PIN Y10 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[3]}]
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[3]}]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[4]}]
set_property -dict {PACKAGE_PIN AA11 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[4]}]
set_property -dict {PACKAGE_PIN AB13 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[5]}]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[5]}]
set_property -dict {PACKAGE_PIN AC10 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[6]}]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[6]}]
set_property -dict {PACKAGE_PIN AE8 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[7]}]
set_property -dict {PACKAGE_PIN AD8 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[7]}]
set_property -dict {PACKAGE_PIN AC11 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[8]}]
set_property -dict {PACKAGE_PIN AC12 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[8]}]
set_property -dict {PACKAGE_PIN AE9 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[9]}]
set_property -dict {PACKAGE_PIN AD9 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[9]}]
set_property -dict {PACKAGE_PIN AF11 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[10]}]
set_property -dict {PACKAGE_PIN AE11 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[10]}]
set_property -dict {PACKAGE_PIN AD11 IOSTANDARD LVDS} [get_ports {lvds_pre_n_inout_pad[11]}]
set_property -dict {PACKAGE_PIN AD12 IOSTANDARD LVDS} [get_ports {lvds_pre_p_inout_pad[11]}]

# --------------------------------- LRM RS485 ----------------------------------
set_property -dict {PACKAGE_PIN AA26 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_den_out_pad[0]}]
set_property -dict {PACKAGE_PIN AD24 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_ren_out_pad[0]}]
set_property -dict {PACKAGE_PIN AF25 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_rxd_in_pad[0]}]
set_property -dict {PACKAGE_PIN Y28 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_txd_out_pad[0]}]

set_property -dict {PACKAGE_PIN AE25 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_den_out_pad[1]}]
set_property -dict {PACKAGE_PIN Y26 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_ren_out_pad[1]}]
set_property -dict {PACKAGE_PIN AA28 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_rxd_in_pad[1]}]
set_property -dict {PACKAGE_PIN AG25 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_txd_out_pad[1]}]

set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_den_out_pad[2]}]
set_property -dict {PACKAGE_PIN AK20 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_ren_out_pad[2]}]
set_property -dict {PACKAGE_PIN AK21 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_rxd_in_pad[2]}]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_txd_out_pad[2]}]

set_property -dict {PACKAGE_PIN AH21 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_den_out_pad[3]}]
set_property -dict {PACKAGE_PIN AE21 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_ren_out_pad[3]}]
set_property -dict {PACKAGE_PIN AD22 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_rxd_in_pad[3]}]
set_property -dict {PACKAGE_PIN AF20 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_txd_out_pad[3]}]

set_property -dict {PACKAGE_PIN W28 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_den_out_pad[4]}]
set_property -dict {PACKAGE_PIN Y24 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_ren_out_pad[4]}]
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_rxd_in_pad[4]}]
set_property -dict {PACKAGE_PIN Y29 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_txd_out_pad[4]}]

set_property -dict {PACKAGE_PIN AH20 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_den_out_pad[5]}]
set_property -dict {PACKAGE_PIN AG20 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_ren_out_pad[5]}]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_rxd_in_pad[5]}]
set_property -dict {PACKAGE_PIN AJ21 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_txd_out_pad[5]}]

set_property -dict {PACKAGE_PIN AC25 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_den_out_pad[6]}]
set_property -dict {PACKAGE_PIN AB23 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_ren_out_pad[6]}]
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_rxd_in_pad[6]}]
set_property -dict {PACKAGE_PIN AC22 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_txd_out_pad[6]}]

set_property -dict {PACKAGE_PIN AH22 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_den_out_pad[7]}]
set_property -dict {PACKAGE_PIN AF21 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_ren_out_pad[7]}]
set_property -dict {PACKAGE_PIN AC20 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_rxd_in_pad[7]}]
set_property -dict {PACKAGE_PIN AD21 IOSTANDARD LVCMOS33} [get_ports {lrm_rs485_txd_out_pad[7]}]

# ---------------------------------- LRM LVDS ----------------------------------
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[0]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[0]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[0]}]
set_property PACKAGE_PIN AH2 [get_ports {lrm_lvds_p_inout_pad[0]}]
set_property PACKAGE_PIN AJ2 [get_ports {lrm_lvds_n_inout_pad[0]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[0]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[0]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[0]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[1]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[1]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[1]}]
set_property PACKAGE_PIN AE1 [get_ports {lrm_lvds_p_inout_pad[1]}]
set_property PACKAGE_PIN AF1 [get_ports {lrm_lvds_n_inout_pad[1]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[1]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[1]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[1]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[2]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[2]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[2]}]
set_property PACKAGE_PIN AG2 [get_ports {lrm_lvds_p_inout_pad[2]}]
set_property PACKAGE_PIN AH1 [get_ports {lrm_lvds_n_inout_pad[2]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[2]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[2]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[2]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[3]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[3]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[3]}]
set_property PACKAGE_PIN AJ1 [get_ports {lrm_lvds_p_inout_pad[3]}]
set_property PACKAGE_PIN AK1 [get_ports {lrm_lvds_n_inout_pad[3]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[3]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[3]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[3]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[4]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[4]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[4]}]
set_property PACKAGE_PIN AJ3 [get_ports {lrm_lvds_p_inout_pad[4]}]
set_property PACKAGE_PIN AK3 [get_ports {lrm_lvds_n_inout_pad[4]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[4]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[4]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[4]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[5]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[5]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[5]}]
set_property PACKAGE_PIN AD2 [get_ports {lrm_lvds_p_inout_pad[5]}]
set_property PACKAGE_PIN AD1 [get_ports {lrm_lvds_n_inout_pad[5]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[5]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[5]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[5]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[6]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[6]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[6]}]
set_property PACKAGE_PIN AF3 [get_ports {lrm_lvds_p_inout_pad[6]}]
set_property PACKAGE_PIN AF2 [get_ports {lrm_lvds_n_inout_pad[6]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[6]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[6]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[6]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[7]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[7]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[7]}]
set_property PACKAGE_PIN AC2 [get_ports {lrm_lvds_p_inout_pad[7]}]
set_property PACKAGE_PIN AC1 [get_ports {lrm_lvds_n_inout_pad[7]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[7]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[7]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[7]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[8]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[8]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[8]}]
set_property PACKAGE_PIN AF7 [get_ports {lrm_lvds_p_inout_pad[8]}]
set_property PACKAGE_PIN AG7 [get_ports {lrm_lvds_n_inout_pad[8]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[8]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[8]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[8]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[9]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[9]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[9]}]
set_property PACKAGE_PIN AD4 [get_ports {lrm_lvds_p_inout_pad[9]}]
set_property PACKAGE_PIN AD3 [get_ports {lrm_lvds_n_inout_pad[9]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[9]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[9]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[9]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[10]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[10]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[10]}]
set_property PACKAGE_PIN AE4 [get_ports {lrm_lvds_p_inout_pad[10]}]
set_property PACKAGE_PIN AE3 [get_ports {lrm_lvds_n_inout_pad[10]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[10]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[10]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[10]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[11]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[11]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[11]}]
set_property PACKAGE_PIN AG4 [get_ports {lrm_lvds_p_inout_pad[11]}]
set_property PACKAGE_PIN AG3 [get_ports {lrm_lvds_n_inout_pad[11]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[11]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[11]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[11]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[12]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[12]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[12]}]
set_property PACKAGE_PIN AF8 [get_ports {lrm_lvds_p_inout_pad[12]}]
set_property PACKAGE_PIN AG8 [get_ports {lrm_lvds_n_inout_pad[12]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[12]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[12]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[12]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[13]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[13]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[13]}]
set_property PACKAGE_PIN AC14 [get_ports {lrm_lvds_p_inout_pad[13]}]
set_property PACKAGE_PIN AD14 [get_ports {lrm_lvds_n_inout_pad[13]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[13]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[13]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[13]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[14]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[14]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[14]}]
set_property PACKAGE_PIN AC5 [get_ports {lrm_lvds_p_inout_pad[14]}]
set_property PACKAGE_PIN AC4 [get_ports {lrm_lvds_n_inout_pad[14]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[14]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[14]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[14]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[15]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[15]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[15]}]
set_property PACKAGE_PIN AG15 [get_ports {lrm_lvds_p_inout_pad[15]}]
set_property PACKAGE_PIN AH15 [get_ports {lrm_lvds_n_inout_pad[15]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[15]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[15]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[15]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[16]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[16]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[16]}]
set_property PACKAGE_PIN AF15 [get_ports {lrm_lvds_p_inout_pad[16]}]
set_property PACKAGE_PIN AG14 [get_ports {lrm_lvds_n_inout_pad[16]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[16]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[16]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[16]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[17]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[17]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[17]}]
set_property PACKAGE_PIN AA15 [get_ports {lrm_lvds_p_inout_pad[17]}]
set_property PACKAGE_PIN AB15 [get_ports {lrm_lvds_n_inout_pad[17]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[17]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[17]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[17]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[18]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[18]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[18]}]
set_property PACKAGE_PIN AD6 [get_ports {lrm_lvds_p_inout_pad[18]}]
set_property PACKAGE_PIN AE6 [get_ports {lrm_lvds_n_inout_pad[18]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[18]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[18]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[18]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[19]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[19]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[19]}]
set_property PACKAGE_PIN AK16 [get_ports {lrm_lvds_p_inout_pad[19]}]
set_property PACKAGE_PIN AK15 [get_ports {lrm_lvds_n_inout_pad[19]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[19]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[19]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[19]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[20]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[20]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[20]}]
set_property PACKAGE_PIN AE15 [get_ports {lrm_lvds_p_inout_pad[20]}]
set_property PACKAGE_PIN AE14 [get_ports {lrm_lvds_n_inout_pad[20]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[20]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[20]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[20]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[21]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[21]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[21]}]
set_property PACKAGE_PIN AC16 [get_ports {lrm_lvds_p_inout_pad[21]}]
set_property PACKAGE_PIN AC15 [get_ports {lrm_lvds_n_inout_pad[21]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[21]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[21]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[21]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[22]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[22]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[22]}]
set_property PACKAGE_PIN AC7 [get_ports {lrm_lvds_p_inout_pad[22]}]
set_property PACKAGE_PIN AD7 [get_ports {lrm_lvds_n_inout_pad[22]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[22]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[22]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[22]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[23]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[23]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[23]}]
set_property PACKAGE_PIN AE16 [get_ports {lrm_lvds_p_inout_pad[23]}]
set_property PACKAGE_PIN AF16 [get_ports {lrm_lvds_n_inout_pad[23]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[23]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[23]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[23]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[24]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[24]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[24]}]
set_property PACKAGE_PIN Y16 [get_ports {lrm_lvds_p_inout_pad[24]}]
set_property PACKAGE_PIN Y15 [get_ports {lrm_lvds_n_inout_pad[24]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[24]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[24]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[24]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[25]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[25]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[25]}]
set_property PACKAGE_PIN AH17 [get_ports {lrm_lvds_p_inout_pad[25]}]
set_property PACKAGE_PIN AJ17 [get_ports {lrm_lvds_n_inout_pad[25]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[25]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[25]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[25]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[26]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[26]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[26]}]
set_property PACKAGE_PIN AH16 [get_ports {lrm_lvds_p_inout_pad[26]}]
set_property PACKAGE_PIN AJ16 [get_ports {lrm_lvds_n_inout_pad[26]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[26]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[26]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[26]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[27]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[27]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[27]}]
set_property PACKAGE_PIN AA17 [get_ports {lrm_lvds_p_inout_pad[27]}]
set_property PACKAGE_PIN AA16 [get_ports {lrm_lvds_n_inout_pad[27]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[27]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[27]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[27]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[28]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[28]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[28]}]
set_property PACKAGE_PIN AG19 [get_ports {lrm_lvds_p_inout_pad[28]}]
set_property PACKAGE_PIN AH19 [get_ports {lrm_lvds_n_inout_pad[28]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[28]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[28]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[28]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[29]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[29]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[29]}]
set_property PACKAGE_PIN AJ18 [get_ports {lrm_lvds_p_inout_pad[29]}]
set_property PACKAGE_PIN AK18 [get_ports {lrm_lvds_n_inout_pad[29]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[29]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[29]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[29]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[30]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[30]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[30]}]
set_property PACKAGE_PIN AB17 [get_ports {lrm_lvds_p_inout_pad[30]}]
set_property PACKAGE_PIN AC17 [get_ports {lrm_lvds_n_inout_pad[30]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[30]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[30]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[30]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[31]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[31]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[31]}]
set_property PACKAGE_PIN AD19 [get_ports {lrm_lvds_p_inout_pad[31]}]
set_property PACKAGE_PIN AE19 [get_ports {lrm_lvds_n_inout_pad[31]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[31]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[31]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[31]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[32]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[32]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[32]}]
set_property PACKAGE_PIN AA18 [get_ports {lrm_lvds_p_inout_pad[32]}]
set_property PACKAGE_PIN AB18 [get_ports {lrm_lvds_n_inout_pad[32]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[32]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[32]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[32]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[33]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[33]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[33]}]
set_property PACKAGE_PIN Y19 [get_ports {lrm_lvds_p_inout_pad[33]}]
set_property PACKAGE_PIN Y18 [get_ports {lrm_lvds_n_inout_pad[33]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[33]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[33]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[33]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[34]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[34]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[34]}]
set_property PACKAGE_PIN AJ19 [get_ports {lrm_lvds_p_inout_pad[34]}]
set_property PACKAGE_PIN AK19 [get_ports {lrm_lvds_n_inout_pad[34]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[34]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[34]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[34]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_n_inout_pad[35]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_n_inout_pad[35]}]
set_property PULLDOWN true [get_ports {lrm_lvds_n_inout_pad[35]}]
set_property PACKAGE_PIN AB19 [get_ports {lrm_lvds_p_inout_pad[35]}]
set_property PACKAGE_PIN AC19 [get_ports {lrm_lvds_n_inout_pad[35]}]
set_property IOSTANDARD LVDS [get_ports {lrm_lvds_p_inout_pad[35]}]
set_property DIFF_TERM TRUE [get_ports {lrm_lvds_p_inout_pad[35]}]
set_property PULLDOWN true [get_ports {lrm_lvds_p_inout_pad[35]}]

# -------------------------------- GPIO to CPLD --------------------------------
# Originally, these signals are used for mark address, but actually the mark
# address will be written through XINTF bus through CPLD.
set_property -dict {PACKAGE_PIN AA27 IOSTANDARD LVCMOS33} [get_ports {gpo_out_pad[0]}]
set_property -dict {PACKAGE_PIN AB28 IOSTANDARD LVCMOS33} [get_ports {gpo_out_pad[1]}]
set_property -dict {PACKAGE_PIN AA25 IOSTANDARD LVCMOS33} [get_ports {gpo_out_pad[2]}]
set_property -dict {PACKAGE_PIN AB25 IOSTANDARD LVCMOS33} [get_ports {gpo_out_pad[3]}]
set_property -dict {PACKAGE_PIN AC29 IOSTANDARD LVCMOS33} [get_ports {gpo_out_pad[4]}]
set_property -dict {PACKAGE_PIN AC30 IOSTANDARD LVCMOS33} [get_ports {gpo_out_pad[5]}]

# ------------------------------------ LED -------------------------------------
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {board_led_out_pad[0]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {board_led_out_pad[1]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {board_led_out_pad[2]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {board_led_out_pad[3]}]
set_property -dict {PACKAGE_PIN AD27 IOSTANDARD LVCMOS33} [get_ports {debug_led_out_pad[0]}]
set_property -dict {PACKAGE_PIN AB30 IOSTANDARD LVCMOS33} [get_ports {debug_led_out_pad[1]}]


# set_property -dict {PACKAGE_PIN N27    IOSTANDARD LVCMOS33} [get_ports TD4_TIMIN]
# set_property -dict {PACKAGE_PIN K28    IOSTANDARD LVCMOS33} [get_ports TD4_TIMOUT]

# set_property -dict {PACKAGE_PIN AB27   IOSTANDARD LVCMOS33} [get_ports FPGA4_SCL]
# set_property -dict {PACKAGE_PIN AC27   IOSTANDARD LVCMOS33} [get_ports FPGA4_SDA]

# set_property -dict {PACKAGE_PIN Y30    IOSTANDARD LVCMOS33} [get_ports CPLD_FPGA4_LS0]
# set_property -dict {PACKAGE_PIN AA30   IOSTANDARD LVCMOS33} [get_ports CPLD_FPGA4_LS1]


